- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    docker_distro_release: "{{ ansible_distribution_release if ansible_distribution_release != 'eoan' else 'disco' }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install Docker pre-requisites
      become: yes
      apt:
        package: gnupg-agent
      when: not is_mac

    - name: Install Docker CLI components (Linux)
      become: yes
      apt:
        update_cache: yes
        package: "{{ item }}"
      loop:
        - docker.io
        - docker-compose
      when: not is_mac

    - name: Enable Docker engine for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes
      when: not is_mac and not is_wsl

    # macOS

    - name: Install Docker CLI components (macOS)
      homebrew:
        name: docker-compose
      when: is_mac

    - name: Install Docker engine (macOS)
      homebrew_cask:
        name: docker
      when: is_mac
